version: '3.8'

services:
  app:
    build:
      context: .
      target: prod   # ✅ Ensures production doesn't use a volume
    ports:
      - "83:3000"
    depends_on:
      - redis

  redis:
    image: redis:7
