version: '3.8'

services:
  app:
    build:
      context: .
      target: prod   
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7
